BEGIN
    DECLARE a AS INTEGER
    DECLARE b AS INTEGER
    DECLARE luas AS LONG LONG

    PRINT "SELAMAT DATANG DI KALKULATOR LUAS PERSEGI PANJANG."
    PRINT "SILAHAKAN MASUKKAN PANJANG DAN LEBAR DARI PERSEGI PANJANG YANG INGIN ANDA HITUNG."

    PRINT "PANJANG : "
    INPUT a

    PRINT "LEBAR : "
    INPUT b

    SET luas = a * b

    PRINT "LUAS PERSEGI PANJANG : " + luas
END
